#!/usr/bin/python

"""
    RTE Player
    slacklinucs@gmail.com
"""

MODE_MAINMENU    = 'MAINMENU'
MODE_CREATEMENU  = 'CREATEMENU'
MODE_LIVEMENU    = 'LIVEMENU'
MODE_GETEPISODES = 'GETEPISODES'
MODE_PLAYVIDEO   = 'PLAYVIDEO'
MODE_PLAYRADIO   = 'PLAYRADIO'
MODE_CATEGORY    = 'CATEGORY'
MODE_ATOZ        = 'ATOZ'